# domain/backtest/strategies/modifiers/base.py
"""Abstract base class for signal modifiers."""
from abc import ABC, abstractmethod

from domain.backtest.models import Signal, SignalContext


class SignalModifier(ABC):
    """Abstract base class for signal modifiers that filter or transform signals.

    SignalModifiers are used in composite strategies to filter, adjust, or block
    signals generated by a primary strategy based on additional conditions.

    Example modifiers:
    - MAFilter: Block signals that go against the moving average trend
    - VolatilityFilter: Reduce position size in high volatility periods
    - ConfirmationFilter: Require multiple indicators to confirm signal

    Usage:
        modifier = MAFilter(window=20, trend_confirm=True)
        result = modifier.modify(signal, context)
        if result is None:
            reason = modifier.explain_block(signal, context)
            # Log or display the reason
    """

    @abstractmethod
    def name(self) -> str:
        """Get modifier name for display.

        Returns:
            Human-readable name with key parameters, e.g., "MAFilter(20, trend_confirm)"
        """
        raise NotImplementedError

    @abstractmethod
    def modify(self, signal: Signal, context: SignalContext) -> Signal | None:
        """Modify or block a signal based on additional conditions.

        Args:
            signal: The original signal from the primary strategy
            context: Context information including date, nav, and indicators

        Returns:
            - Modified Signal if the signal passes through (possibly adjusted)
            - None if the signal should be blocked
        """
        raise NotImplementedError

    @abstractmethod
    def explain_block(self, signal: Signal, context: SignalContext) -> str:
        """Explain why a signal was blocked.

        This method should provide a clear, human-readable explanation
        of why the modifier blocked a particular signal.

        Args:
            signal: The blocked signal
            context: Context information at the time of blocking

        Returns:
            Human-readable explanation string
        """
        raise NotImplementedError